version: "2"
prepare:
  fetch:
    - url:  "https://raw.githubusercontent.com/runtastic/rt_rubocop_defaults/master/config/default.yml"
      path: .rt_rubocop_defaults.yml
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-77
    config:
      file: .rubocop_codeclimate.yml
  bundler-audit:
    enabled: true
  git-legal:
    enabled: true
