language: ruby
cache: bundler
rvm:
  - 2.3.5
  - 2.4.4
  - 2.5.3
  - 2.6.1
  - jruby-9.1.17.0
  - jruby-9.2.5.0
jdk:
  - oraclejdk11
env:
  global:
    - CC_TEST_REPORTER_ID=9fd6c503f8bb89483410c1fc0578e5845c3fe0d3e773a32eb2788713fb101a93
  matrix:
    - "JRUBY_OPTS='--dev --debug'"
    - "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"

matrix:
  exclude:
    - rvm: 2.3.5
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: 2.4.4
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: 2.5.3
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: 2.6.1
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: truffleruby
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
  allow_failures:
    - rvm: jruby-9.1.17.0
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: jruby-9.2.5.0
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"

services:
  - redis-server

before_install:
 - gem update --system
 - gem install bundler -v "~> 1.0"
 - gem install bundler -v "~> 2.0"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
