language: ruby
cache: bundler
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - jruby-9.2.10.0
  - jruby-9.1.17.0
  # https://github.com/oracle/truffleruby/issues/1398
  - truffleruby-20.0.0
jdk:
  - oraclejdk11
env:
  global:
    - CC_TEST_REPORTER_ID=7b2f0f3c9e20e50573e293fe3743a322a74e54087f95abc98d0f1dd1f3dd0a97
    - TRUFFLERUBYOPT=--debug
    - JRUBY_OPTS=--debug
  matrix:
    - "JRUBY_OPTS='--dev'"
    - "JRUBY_OPTS='-Xcompile.invokedynamic=true'"

matrix:
  exclude:
    - rvm: 2.7.0
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true'"
    - rvm: 2.6.5
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true'"
    - rvm: 2.5.7
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true'"
    - rvm: 2.4.9
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true'"
  allow_failures:
    - rvm: 2.4.9
    - rvm: truffleruby-20.0.0
    - env: "JRUBY_OPTS='-Xcompile.invokedynamic=true'"
services:
  - redis-server

# before_install:
#  - gem update --system
#   - gem install bundler -v "1.17.3"
#  - gem install bundler -v "2.0.2"
#  - gem update bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - COVERAGE=true bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
